############# English navigation ##############

# main menu (empty - navbar menu removed)

# footer menu
[[footer]]
name = "Support"
url = "support/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2

[[footer]]
name = "Terms"
url = "terms/"
weight = 3
